Add Travis-CI badges on landing page
heremaps/heremaps.github.io pull request #9
Opened 2017-05-23 15:07 UTC by freethan

This is about adding Travis-CI badges where applicable

2017-05-23 15:13 UTC, sschuberth requested changes

2017-05-23 15:13 UTC, sschuberth commented on index.html
> +						travis_ci_build_branch: 'master'
The branch should be `gh-pages` in this case.

2017-05-23 15:55 UTC, freethan commented on index.html
> +						travis_ci_build_branch: 'master'
Correct, fixed with 714c97b

2017-05-24 07:01 UTC, sschuberth commented
FYI, RawGit URL for previewing: https://rawgit.com/heremaps/heremaps.github.io/travis-ci-build-status/index.html

2017-05-24 07:01 UTC, sschuberth approved these changes

2017-05-24 09:53 UTC, merged